### ISSUE TITLE
请问如何实现vue项目的自动化构建？

### ISSUE THREAD

**Issue by stonemakers** [zczhangchao51/fjpublish#2]
目前发布的方式：
本地有一个vue2.0的项目，阿里云服务器上直接git clone此项目，然后每次都是ssh到服务器上进行同步代码，然后npm run build,再通过nginx指向dist文件夹实现网页的发布。

使用了fjpublish的方式：
我希望是直接在本地执行一段话，直接ssh远程服务器，然后将本地的npm run build 后的dist文件夹直接上传到服务器上对应的文件夹即可。 
问题来了。。没有找到如何配置发布前git pull 的设置。。默认配置的时候会一直git pull，无法下一步

**Comment by zczhangchao51** [comment]
好好看文档😂，使用fjpublish不需要做那么多事情，老老实实在本机写代码，要发布的是敲fjpublish的命令，让它自动化完成整个过程，你就可以去泡茶逗猫了。
