### ISSUE TITLE
不知道作者有没有考虑做ftp协议的工具呢？

### ISSUE THREAD

**Issue by amdun** [zczhangchao51/fjpublish#4]
今天花了一下午的时间了解了一下作者的这个工具，感觉太强大了，对前端来说真的是一个神器。但很可惜我们公司用的文件传输协议是ftp，貌似就没法用这个工具了，只能每次修改了文件之后都重复git、编译、连ftp、打开相应目录、上传这些动作，一天重复几十次……

所以冒昧问一下作者有没有考虑做ftp上传的工具呢？

**Comment by zczhangchao51** [comment]
@amdun 通常scp也是可以用的，fjpublish也是用的scp，所以不用关心太多，只需要按文档配置好，然后测试一下就知道了。
